### ISSUE TITLE
Vector for classifier.py

### ISSUE THREAD

**Issue by Flolau** [kocko/rumour-eval#7]
Hi, the file data/vector.json you load in classifier.py is missing.

**Comment by kocko** [comment]
Hello, thanks for the feedback!

You have to first run the `feature/feature_extractor.py` script. It will generate the `vector.json` file.

I understand there are many issues like temporal coupling, small vector space and others related to the code style, but we are still working on this project. It involves a lot of research and we are still doing experiments. I hope that in near future we'll teach a much _clever_ classifier and much easier-to-use system. :)
